import React,{useEffect,useState} from 'react';
import {ActivityIndicator,AppState,KeyboardAvoidingView,Modal,Platform,Pressable,ScrollView,Text,View,useWindowDimensions} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import type {Session} from '@supabase/supabase-js';
import {supabase} from './src/lib/supabase';
import {useGym} from './src/lib/useGym';
import {daily,exercises,filterRecords,stats,today,volume,type Workout} from './src/lib/model';
import {Button,Card,Field,C,s,Label} from './src/components/ui';
import {ExercisePicker} from './src/components/ExercisePicker';
const num=(n:number)=>n.toLocaleString('es-BO',{maximumFractionDigits:1});
const dayLabel=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('es-BO',{day:'numeric',month:'short'});
const errorText=(e:unknown)=>e instanceof Error?e.message:'No se pudo completar la operación. Inténtalo de nuevo.';
function Brand(){return <View style={s.row}><View style={{backgroundColor:C.lime,width:34,height:34,borderRadius:10,justifyContent:'center',alignItems:'center'}}><Text style={{fontSize:24,color:C.dark,fontWeight:'900'}}>r</Text></View><Text style={{fontSize:26,fontWeight:'800',color:C.text,letterSpacing:-1}}>ritmo<Text style={{color:C.lime}}> .</Text></Text></View>}
export default function App(){
 const [session,setSession]=useState<Session|null>(null);const [loading,setLoading]=useState(!!supabase);const [guest,setGuest]=useState(false);const [bootError,setBootError]=useState('');
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data,error})=>{if(error)setBootError(error.message);setSession(data.session);setLoading(false)}).catch(()=>{setBootError('No se pudo recuperar la sesión.');setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setLoading(false)});const sub=AppState.addEventListener('change',state=>{if(state==='active')supabase?.auth.startAutoRefresh();else supabase?.auth.stopAutoRefresh()});return()=>{data.subscription.unsubscribe();sub.remove()};},[]);
 return <View style={s.page}><StatusBar style="light"/>{loading?<View style={{flex:1,justifyContent:'center'}}><ActivityIndicator color={C.lime}/></View>:session||guest?<Home key={session?.user.id||'guest'} owner={session?.user.id||'guest'} email={session?.user.email||'Modo local'} guest={!session} onExit={async()=>{if(session){const {error}=await supabase!.auth.signOut({scope:'local'});if(error)throw error;}setGuest(false);}}/>:<Auth onGuest={()=>setGuest(true)} bootError={bootError}/>}</View>
}
function Auth({onGuest,bootError}:{onGuest:()=>void;bootError:string}){
 const [mode,setMode]=useState<'login'|'signup'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState(bootError);
 async function submit(){setNotice('');if(!supabase){setNotice('Estamos preparando la conexión de cuentas. Mientras tanto puedes usar el modo local.');return;}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())||password.length<8){setNotice('Introduce un correo válido y una contraseña de al menos 8 caracteres.');return;}setBusy(true);try{const result=mode==='login'?await supabase.auth.signInWithPassword({email:email.trim(),password}):await supabase.auth.signUp({email:email.trim(),password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session)setNotice('Revisa tu correo para confirmar tu cuenta. Luego vuelve e inicia sesión.');}catch(e){setNotice(errorText(e));}finally{setBusy(false);}}
 return <ScrollView contentContainerStyle={{flexGrow:1,justifyContent:'center',padding:24}} keyboardShouldPersistTaps="handled"><View style={{maxWidth:980,width:'100%',alignSelf:'center',gap:38}}><Brand/><View style={[s.row,{alignItems:'center',gap:60}]}><View style={{flex:1,minWidth:260,gap:22}}><Text style={{color:C.lime,fontSize:14,letterSpacing:2,fontWeight:'600'}}>TU DIARIO DE ENTRENAMIENTO</Text><Text style={[s.title,{fontSize:52,lineHeight:57}]}>Cada serie{ '\n'}cuenta.</Text><Text style={[s.text,{color:C.muted,maxWidth:400}]}>Registra lo que levantas. Mira cuánto avanzas. Lleva tu progreso contigo, incluso sin conexión.</Text><View style={{gap:12,marginTop:16}}>{['01   Registra tus ejercicios y series','02   Sigue tu volumen y tus marcas','03   Sincroniza al volver a conectarte'].map(t=><Text key={t} style={s.text}>{t}</Text>)}</View></View><Card style={{flex:1,minWidth:280,maxWidth:450}}><Text style={s.h2}>{mode==='login'?'Vuelve a tu ritmo':'Crea tu cuenta'}</Text><Text style={s.muted}>Tu entrenamiento, en todos tus dispositivos.</Text><Field label="Correo electrónico" placeholder="tu@correo.com" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" autoComplete="email"/><Field label="Contraseña" placeholder="Mínimo 8 caracteres" secureTextEntry value={password} onChangeText={setPassword} autoComplete={mode==='signup'?'new-password':'current-password'} onSubmitEditing={()=>void submit()}/>{!!notice&&<Text accessibilityRole="alert" style={s.error}>{notice}</Text>}<Button disabled={busy} title={busy?'Un momento…':mode==='login'?'Iniciar sesión →':'Crear cuenta →'} onPress={()=>void submit()}/><Button secondary title={mode==='login'?'No tengo cuenta · Registrarme':'Ya tengo cuenta · Iniciar sesión'} onPress={()=>{setMode(mode==='login'?'signup':'login');setNotice('')}}/><View style={s.divider}/><Button secondary title="Probar en este dispositivo" onPress={onGuest}/><Text style={s.muted}>El modo local guarda datos solo aquí y no los vincula a una cuenta. {supabase?'Para crear una cuenta necesitas conexión.':'El acceso y la sincronización estarán disponibles al conectar Supabase.'}</Text></Card></View></View></ScrollView>
}
function Home({owner,email,guest,onExit}:{owner:string;email:string;guest:boolean;onExit:()=>Promise<void>}){
 const gym=useGym(owner,guest);const {width}=useWindowDimensions();const compact=width<760;
 const [tab,setTab]=useState<'dashboard'|'history'>('dashboard');const [filter,setFilter]=useState('all');const [period,setPeriod]=useState('30');const [from,setFrom]=useState('');const [to,setTo]=useState(today());const [open,setOpen]=useState(false);const [removeId,setRemoveId]=useState<string|null>(null);const [notice,setNotice]=useState('');const [exitOpen,setExitOpen]=useState(false);const [deleting,setDeleting]=useState(false);
 const start=new Date();start.setDate(start.getDate()-(Number(period)-1));const startDate=`${start.getFullYear()}-${String(start.getMonth()+1).padStart(2,'0')}-${String(start.getDate()).padStart(2,'0')}`;
 const invalidRange=period==='custom'&&(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to);
 const filtered=invalidRange?[]:filterRecords(gym.all,filter,period==='all'?'':period==='custom'?from:startDate,period==='custom'?to:today());const summary=stats(filtered);const days=daily(filtered);const max=Math.max(1,...days.map(d=>d.value));
 const groups=exercises.map(e=>({...e,value:filtered.filter(w=>w.exerciseId===e.id).reduce((n,w)=>n+volume(w),0)})).filter(e=>e.value>0).sort((a,b)=>b.value-a.value).slice(0,5);
 const chartWidth=Math.max(340,days.length*58);const best=filtered.length?Math.max(...filtered.flatMap(w=>w.sets.map(r=>r.kg))):0;
 return <><ScrollView contentContainerStyle={[s.wrap,compact&&{padding:16,paddingTop:30}]}><View style={s.between}><Brand/><View style={s.row}><Text style={s.muted}>{guest?'Modo local':email}</Text><Button small secondary title="Salir" onPress={()=>setExitOpen(true)}/></View></View><View style={s.divider}/><View style={s.between}><View style={s.row}>{(['dashboard','history'] as const).map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>setTab(t)} style={[s.pill,tab===t&&{backgroundColor:C.lime,borderColor:C.lime}]}><Text style={{color:tab===t?C.dark:C.muted,fontSize:15,fontWeight:'600'}}>{t==='dashboard'?'Mi progreso':'Historial'}</Text></Pressable>)}</View><Text style={[s.muted,{color:gym.pending?C.lime:C.muted}]}>{guest?'● Solo en este dispositivo':`● ${gym.syncStatus}${gym.pending?` · ${gym.pending} pendientes`:''}`}</Text></View>
 <View style={s.between}><View style={{gap:7,maxWidth:'100%'}}><Text style={{color:C.lime,fontSize:13,letterSpacing:2}}>ENTRENA. REGISTRA. REPITE.</Text><Text style={s.title}>{tab==='dashboard'?'Tu esfuerzo, en perspectiva.':'Tu diario de entrenamiento.'}</Text><Text style={s.muted}>{new Date().toLocaleDateString('es-BO',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}</Text></View><Button disabled={!gym.ready} title="+  Registrar entrenamiento" onPress={()=>setOpen(true)}/></View>
 {!!gym.error&&<Text style={s.error}>{gym.error}</Text>}{!!notice&&<Pressable onPress={()=>setNotice('')}><Text accessibilityRole="alert" style={[s.text,{color:C.lime}]}>{notice}</Text></Pressable>}
 <View style={s.between}><ExercisePicker value={filter} onChange={setFilter} allowAll/><View style={s.row}>{[['7','7 días'],['30','30 días'],['90','90 días'],['all','Todo'],['custom','Fechas']].map(([v,label])=><Pressable key={v} accessibilityRole="button" accessibilityState={{selected:period===v}} onPress={()=>setPeriod(v!)} style={[s.pill,period===v&&{backgroundColor:C.panel,borderColor:C.lime}]}><Text style={{color:period===v?C.lime:C.muted,fontSize:14}}>{label}</Text></Pressable>)}</View></View>
 {period==='custom'&&<View style={s.row}><Field label="Desde (AAAA-MM-DD)" value={from} placeholder="2026-09-01" onChangeText={setFrom}/><Field label="Hasta (AAAA-MM-DD)" value={to} onChangeText={setTo}/>{invalidRange&&<Text style={s.error}>Revisa las fechas: el inicio debe ser anterior al final.</Text>}</View>}
 {!gym.ready?<ActivityIndicator color={C.lime}/>:<>{tab==='dashboard'&&<><View style={[s.row,{alignItems:'stretch'}]}>{[{label:'VOLUMEN TOTAL',value:num(summary.volume),unit:'kg',accent:true},{label:'DÍAS ENTRENADOS',value:String(summary.sessions),unit:summary.sessions===1?'día':'días'},{label:'SERIES COMPLETADAS',value:String(summary.sets),unit:'series'},{label:'REPETICIONES',value:num(summary.reps),unit:'reps'}].map(m=><Card key={m.label} style={{flex:1,minWidth:compact?140:180,backgroundColor:m.accent?C.lime:C.panel,borderColor:m.accent?C.lime:C.edge}}><Text style={{fontSize:12,letterSpacing:1,color:m.accent?'#425529':C.muted,fontWeight:'600'}}>{m.label}</Text><Text style={{fontSize:34,fontWeight:'700',color:m.accent?C.dark:C.text,letterSpacing:-1}}>{m.value} <Text style={{fontSize:14,fontWeight:'400'}}>{m.unit}</Text></Text></Card>)}</View>
 <View style={[s.row,{alignItems:'stretch'}]}><Card style={{flex:2,minWidth:compact?280:480}}><View style={s.between}><View style={{gap:5}}><Text style={s.h2}>Volumen por día</Text><Text style={s.muted}>Suma de peso × repeticiones de cada serie</Text></View><Text style={{color:C.lime,fontSize:14}}>● kg levantados</Text></View>{days.length?<ScrollView horizontal showsHorizontalScrollIndicator contentContainerStyle={{flexGrow:1}}><View style={{flex:1,minWidth:chartWidth,paddingTop:10}}><View style={{height:210,flexDirection:'row',gap:10,alignItems:'flex-end',borderBottomWidth:1,borderColor:C.edge}}>{days.map((d,i)=><View key={d.date} style={{flex:1,minWidth:45,alignItems:'center',gap:8}}><Text style={[s.muted,{fontSize:12}]}>{num(d.value)}</Text><View accessibilityLabel={`${dayLabel(d.date)}: ${num(d.value)} kilogramos`} style={{height:Math.max(3,d.value/max*160),width:'65%',maxWidth:48,borderTopLeftRadius:7,borderTopRightRadius:7,backgroundColor:i===days.length-1?C.lime:'#617C45'}}/></View>)}</View><View style={{flexDirection:'row',gap:10,paddingTop:12}}>{days.map(d=><Text key={d.date} style={[s.muted,{flex:1,minWidth:45,textAlign:'center',fontSize:12}]}>{dayLabel(d.date)}</Text>)}</View></View></ScrollView>:<Empty title="Tu progreso empieza con una serie." text="Registra tu primer entrenamiento para ver cómo crece tu volumen."/>}</Card>
 <Card style={{flex:1,minWidth:260}}><Text style={s.h2}>{filter==='all'?'Volumen por ejercicio':'Tu mejor carga'}</Text>{filter==='all'?groups.length?groups.map(g=><View key={g.id} style={{gap:9}}><View style={s.between}><Text style={[s.text,{fontSize:14}]}>{g.name}</Text><Text style={s.muted}>{num(g.value)} kg</Text></View><View style={{height:6,backgroundColor:C.edge,borderRadius:3}}><View style={{height:6,width:`${g.value/(groups[0]?.value||1)*100}%`,backgroundColor:C.lime,borderRadius:3}}/></View></View>):<Empty title="Sin datos todavía" text="Aquí verás tus ejercicios con más volumen."/>:<><Text style={{fontSize:56,color:C.lime,fontWeight:'700'}}>{num(best)} <Text style={s.muted}>kg</Text></Text><Text style={s.muted}>Mayor peso registrado en una serie dentro del periodo seleccionado.</Text><Text style={s.h2}>Carga máxima por día</Text>{days.map(d=>{const kg=Math.max(...filtered.filter(w=>w.date===d.date).flatMap(w=>w.sets.map(r=>r.kg)));return <View key={d.date} style={{gap:6}}><View style={s.between}><Text style={s.muted}>{dayLabel(d.date)}</Text><Text style={s.text}>{num(kg)} kg</Text></View><View style={{height:5,width:`${Math.max(1,kg/(best||1)*100)}%`,backgroundColor:C.lime,borderRadius:3}}/></View>})}</>}</Card></View></>}
 <Card><View style={s.between}><Text style={s.h2}>{tab==='dashboard'?'Últimos registros':'Entrenamientos registrados'}</Text><Text style={s.muted}>{filtered.length} ejercicios registrados</Text></View>{!filtered.length?<Empty title="Sin entrenamientos en este periodo" text={gym.all.length?'Prueba otro ejercicio o cambia el periodo.':'Pulsa «Registrar entrenamiento» para añadir fecha, ejercicio y series.'}/>:filtered.slice(0,tab==='dashboard'?5:undefined).map(w=><View key={w.id} style={{gap:12,paddingVertical:12,borderTopWidth:1,borderColor:C.edge}}><View style={s.between}><View style={{gap:4,flex:1,minWidth:170}}><Text style={s.text}>{exercises.find(e=>e.id===w.exerciseId)?.name}</Text><Text style={s.muted}>{dayLabel(w.date)} {w.date.slice(0,4)} · {w.sets.length} series · {w.sets.reduce((n,r)=>n+r.reps,0)} reps</Text></View><Text style={{color:C.lime,fontSize:18,fontWeight:'600'}}>{num(volume(w))} kg</Text><Button small secondary title="Eliminar" onPress={()=>setRemoveId(w.id)}/></View><Text style={s.muted}>{w.sets.map(r=>`${r.reps} × ${num(r.kg)} kg`).join('   /   ')}</Text>{!!w.notes&&<Text style={s.muted}>{w.notes}</Text>}</View>)}</Card><View style={s.between}><Text style={s.muted}>El volumen mide carga acumulada; no calorías ni trabajo mecánico.</Text>{!guest&&<Button small secondary title="Sincronizar ahora" onPress={()=>void gym.sync()}/>}</View></>}
 </ScrollView><WorkoutForm open={open} onClose={()=>setOpen(false)} onSave={async w=>{await gym.save(w);setNotice('Entrenamiento guardado en este dispositivo.');setOpen(false);}}/>
 <Confirm open={!!removeId} title="¿Eliminar este registro?" text="Se quitará del historial y del dashboard. El cambio se enviará cuando haya conexión." busy={deleting} onCancel={()=>setRemoveId(null)} onConfirm={async()=>{setDeleting(true);try{await gym.remove(removeId!);setRemoveId(null);setNotice('Registro eliminado.');}catch(e){setNotice(errorText(e))}finally{setDeleting(false)}}}/>
 <Confirm open={exitOpen} title="¿Cerrar sesión?" text={gym.pending?`Tienes ${gym.pending} cambios pendientes. Se conservarán en este dispositivo y se sincronizarán al entrar de nuevo con esta cuenta.`:guest?'Los registros locales se conservarán en este dispositivo.':'Tus registros descargados se conservarán para tu próximo inicio de sesión.'} onCancel={()=>setExitOpen(false)} onConfirm={async()=>{try{await onExit()}catch(e){setNotice(errorText(e));setExitOpen(false)}}}/></>
}
function Empty({title,text}:{title:string;text:string}){return <View style={{paddingVertical:42,alignItems:'center',gap:10}}><Text style={[s.h2,{textAlign:'center',fontSize:18}]}>{title}</Text><Text style={[s.muted,{textAlign:'center',maxWidth:380}]}>{text}</Text></View>}
function Confirm({open,title,text,busy,onCancel,onConfirm}:{open:boolean;title:string;text:string;busy?:boolean;onCancel:()=>void;onConfirm:()=>void}){return <Modal visible={open} transparent onRequestClose={onCancel} animationType="fade"><View style={{flex:1,backgroundColor:'#000B',padding:24,justifyContent:'center'}}><Card style={{maxWidth:460,width:'100%',alignSelf:'center'}}><Text style={s.h2}>{title}</Text><Text style={s.text}>{text}</Text><Button title={busy?'Guardando…':'Confirmar'} disabled={busy} onPress={onConfirm}/><Button title="Cancelar" secondary disabled={busy} onPress={onCancel}/></Card></View></Modal>}
function WorkoutForm({open,onClose,onSave}:{open:boolean;onClose:()=>void;onSave:(w:Workout)=>Promise<void>}){
 const [date,setDate]=useState(today());const [exercise,setExercise]=useState('bench');const [sets,setSets]=useState([{reps:'10',kg:'20'}]);const [notes,setNotes]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{if(open){setDate(today());setSets([{reps:'10',kg:'20'}]);setNotes('');setError('')}},[open]);
 const parsed=sets.map(s=>({reps:s.reps.trim()?Number(s.reps.replace(',','.')):NaN,kg:s.kg.trim()?Number(s.kg.replace(',','.')):NaN}));const total=parsed.reduce((n,r)=>n+r.reps*r.kg,0);
 async function save(){setBusy(true);setError('');try{await onSave({date,exerciseId:exercise,sets:parsed,notes:notes.trim()});}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 return <Modal visible={open} transparent animationType="slide" onRequestClose={()=>{if(!busy)onClose()}}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,backgroundColor:'#000B',justifyContent:'center',padding:16}}><View style={[s.card,{maxWidth:600,width:'100%',maxHeight:'94%',alignSelf:'center',padding:0,overflow:'hidden'}]}><ScrollView contentContainerStyle={{padding:24,gap:20}} keyboardShouldPersistTaps="handled"><View style={s.between}><Text style={s.h2}>Registrar entrenamiento</Text><Button small secondary disabled={busy} title="Cerrar" onPress={onClose}/></View><Field label="Fecha (AAAA-MM-DD)" value={date} onChangeText={setDate} maxLength={10}/><View style={{gap:8}}><Label>Ejercicio</Label><ExercisePicker value={exercise} onChange={setExercise}/></View><View style={{gap:12}}><Text style={s.h2}>Tus series</Text><Text style={s.muted}>Registra el peso total utilizado. En ejercicios sin carga externa, usa 0 kg.</Text>{sets.map((r,i)=><View key={i} style={[s.row,{flexWrap:'nowrap',alignItems:'flex-end'}]}><Text style={[s.muted,{paddingBottom:15,width:18}]}>{i+1}</Text><Field label="Reps" value={r.reps} keyboardType="number-pad" onChangeText={v=>setSets(sets.map((x,j)=>j===i?{...x,reps:v}:x))}/><Field label="Peso (kg)" value={r.kg} keyboardType="decimal-pad" onChangeText={v=>setSets(sets.map((x,j)=>j===i?{...x,kg:v}:x))}/><Button small secondary title={'−'} disabled={sets.length===1} onPress={()=>setSets(sets.filter((_,j)=>j!==i))}/></View>)}<Button secondary title="+ Añadir serie" disabled={sets.length>=50} onPress={()=>setSets([...sets,{...sets[sets.length-1]!}])}/></View><Field label="Notas (opcional)" value={notes} onChangeText={setNotes} placeholder="Cómo te sentiste, técnica, descanso…" multiline maxLength={1000}/><View style={s.between}><Text style={s.muted}>Volumen del ejercicio</Text><Text style={{color:C.lime,fontSize:26,fontWeight:'700'}}>{Number.isFinite(total)?num(total):'—'} kg</Text></View>{!!error&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button title={busy?'Guardando…':'Guardar entrenamiento'} disabled={busy} onPress={()=>void save()}/><Text style={[s.muted,{textAlign:'center'}]}>Se guarda aquí primero, incluso sin internet.</Text></ScrollView></View></KeyboardAvoidingView></Modal>
}
