import test from 'node:test';
import assert from 'node:assert/strict';
import {volume,validateWorkout,records,stats,filterRecords,type Workout,type GymEvent} from '../src/lib/model.ts';
import {GymStore} from '../src/lib/store.ts';
import {synchronize} from '../src/lib/sync.ts';
const workout:Workout={date:'2026-01-01',exerciseId:'bench',sets:[{reps:10,kg:20},{reps:8,kg:25}],notes:''};
const event=(id:string,user='alice'):GymEvent=>({id,user_id:user,kind:'workout',target_id:null,payload:workout,created_at:'2026-01-01T12:00:00Z'});
function memory(){const map=new Map<string,string>();return {getItem:async(k:string)=>map.get(k)??null,setItem:async(k:string,v:string)=>{map.set(k,v)}};}
test('volume uses each set; bodyweight zero still counts reps',()=>{assert.equal(volume(workout),400);assert.equal(volume({...workout,sets:[{reps:12,kg:0}]}),0);assert.equal(stats(records([event('1')])).reps,18)});
test('rejects invalid dates, nonfinite values and fractional reps',()=>{for(const bad of [{...workout,date:'2026-02-30'},{...workout,sets:[{reps:1.5,kg:20}]},{...workout,sets:[{reps:10,kg:NaN}]},{...workout,exerciseId:'unknown'},{...workout,sets:[]}])assert.throws(()=>validateWorkout(bad));validateWorkout(workout)});
test('offline data survives reopening, and users are isolated',async()=>{const storage=memory();await new GymStore(storage,'alice').append(event('1'));assert.equal((await new GymStore(storage,'alice').load()).events.length,1);assert.equal((await new GymStore(storage,'bob').load()).events.length,0);await assert.rejects(new GymStore(storage,'bob').append(event('2')))});
test('network failure keeps every pending change',async()=>{const store=new GymStore(memory(),'alice');await store.append(event('1'));await assert.rejects(synchronize(store,{push:async()=>{throw Error('offline')},pull:async()=>[]}));assert.deepEqual((await store.load()).pending,['1'])});
test('retry after acceptance and failed pull is idempotent',async()=>{const store=new GymStore(memory(),'alice');await store.append(event('1'));const remote=new Map<string,GymEvent>();const push=async(es:GymEvent[])=>{for(const e of es)remote.set(e.id,e)};await assert.rejects(synchronize(store,{push,pull:async()=>{throw Error('lost response')}}));await synchronize(store,{push,pull:async()=>[...remote.values()]});assert.equal(remote.size,1);assert.equal((await store.load()).events.length,1);assert.equal((await store.load()).pending.length,0)});
test('new writes during synchronization remain queued',async()=>{const store=new GymStore(memory(),'alice');await store.append(event('1'));await synchronize(store,{push:async()=>{await store.append(event('2'))},pull:async()=>[event('1'),event('3')]});assert.deepEqual((await store.load()).pending,['2']);assert.equal((await store.load()).events.length,3)});
test('tombstone wins regardless of receive order; no resurrection',()=>{const deletion:GymEvent={...event('2'),kind:'delete',target_id:'1',payload:null};assert.equal(records([deletion,event('1')]).length,0);assert.equal(records([event('1'),deletion]).length,0)});
test('filters use inclusive dates and exercise, sessions count distinct days',()=>{const all=records([event('1'),event('2')]);assert.equal(stats(all).sessions,1);assert.equal(filterRecords(all,'bench','2026-01-01','2026-01-01').length,2);assert.equal(filterRecords(all,'squat','','').length,0)});
test('storage failure is surfaced, never reported as saved',async()=>{const store=new GymStore({getItem:async()=>null,setItem:async()=>{throw Error('quota')}},'alice');await assert.rejects(store.append(event('1')))});
